import { PointOfInterest, POIType, ItemsInLevel } from "@/Types";
const Village = POIType.Village;
const Normal = POIType.Normal;

const pois: ItemsInLevel<PointOfInterest>[] = [];

pois[0] = {
  level: 0,
  items: [
    {
      x: 755.12,
      y: 625.6,
      text: "horsie pasture",
      type: Normal,
    },
    {
      x: 705.2,
      y: 554.56,
      text: "sugarcane shore",
      type: Normal,
    },
    {
      x: 706.96,
      y: 452.8,
      text: "pumpkin paradise",
      type: Normal,
    },
    {
      x: 837.04,
      y: 529.52,
      text: "house hill",
      type: Normal,
    },
    {
      x: 779.68,
      y: 606.24,
      text: "some cows",
      type: Normal,
    },
    {
      x: 98,
      y: 37.6,
      text: "cassie is cute !!!!!",
      type: Normal,
    },
    {
      x: 111.04,
      y: 148.8,
      text: "some sheeps",
      type: Normal,
    },
    {
      x: 734,
      y: 634.4,
      text: "karrot korner",
      type: Normal,
    },
    {
      x: 795.13,
      y: 520.46,
      text: "secret entrance",
      type: Normal,
    },
    {
      x: 752.4,
      y: 607.85,
      text: "entrance to Cursed Cave",
      type: Normal,
    },
    {
      x: 1087.28,
      y: 574.48,
      text: "i made this map while i was lost. it did not help",
      type: Normal,
    },
    {
      x: 194.38,
      y: 156.73,
      text: "mitchama canal on-ramp",
      type: Normal,
    },
    {
      x: 784.47,
      y: 505.15,
      text: "mitchama canal terminus",
      type: Normal,
    },
    {
      x: 52.64,
      y: 46.95,
      text: "forest of illusions",
      type: Normal,
    },
    {
      x: 18.13,
      y: 38.27,
      text: "🍉",
      type: Normal,
    },
    {
      x: 67.39,
      y: 52.14,
      text: "triangle mines entrance",
      type: Normal,
    },
    {
      x: 68.16,
      y: 122.39,
      text: "triangle mines exit",
      type: Normal,
    },
    {
      x: 81.44,
      y: 42.33,
      text: "players' residence",
      type: Normal,
    },
    {
      x: 113.25,
      y: 33.69,
      text: "chaama enclosure",
      type: Normal,
    },
    {
      x: 54.3,
      y: -1.34,
      text: "failed monster trap",
      type: Normal,
    },
    {
      x: 2266.1,
      y: -1302.14,
      text: "crop circles",
      type: Normal,
    },
    {
      x: 2312.86,
      y: -1319.27,
      text: "clown residence for clowns",
      type: Normal,
    },
    {
      x: 2334.99,
      y: -1353.91,
      text: "at it again at pumpkin kremes",
      type: Normal,
    },
    {
      x: 2389.65,
      y: -1360.65,
      text: "sheep",
      type: Normal,
    },
    {
      x: 2401.2,
      y: -1338.9,
      text: "cows",
      type: Normal,
    },
    {
      x: 2460.47,
      y: -1278.85,
      text: "canes",
      type: Normal,
    },
    {
      x: 2364.44,
      y: -1234.01,
      text: "unfinished dock",
      type: Normal,
    },
    {
      x: 2416.79,
      y: -1318.03,
      text: "vatican ravine",
      type: Normal,
    },
    {
      x: 2300.16,
      y: -1169.73,
      text: "path 2 russel village",
      type: Normal,
    },
    {
      x: 664.64,
      y: 462.72,
      text: "path 2 vatican city",
      type: Normal,
    },
    {
      x: 2486.63,
      y: -1355.45,
      text: "open savanna",
      type: Normal,
    },
    {
      x: 35.34,
      y: -118.35,
      text: "sarah's abode",
      type: Normal,
    },
    {
      x: 2295.23,
      y: -1310.99,
      text: "sarah's Machine",
      type: Normal,
    },
    {
      x: 50,
      y: -91,
      text: "also a nether portal that leads to the vatican city path",
      type: Normal,
    },
    {
      x: 840.28,
      y: 408.45,
      text: "slime farm farm",
      type: Normal,
    },
    {
      x: 2378.01,
      y: -1337.17,
      text: "sarah's vacation home",
      type: Normal,
    },
    {
      x: 2345.27,
      y: -1394.69,
      text: "cactus farm farm",
      type: Normal,
    },
    {
      x: 2311.59,
      y: -1332.14,
      text: "portal leading to a path to cuteville",
      type: Normal,
    },
    {
      x: 2299.66,
      y: -1295,
      text: "item sorter interface",
      type: Normal,
    },
  ].map((p) => new PointOfInterest(p, 0)),
};

pois[3] = {
  level: 3,
  items: [
    {
      x: 89.5,
      y: 96.24,
      text: "cuteville",
      type: Village,
    },
    {
      x: 778.24,
      y: 570.64,
      text: "russel village",
      type: Village,
    },
    {
      x: 566.4,
      y: 152.24,
      text: "the sloshy sea",
      type: Normal,
    },
    {
      x: 16.56,
      y: 383.04,
      text: "swamp 👀",
      type: Normal,
    },
    {
      x: 861.12,
      y: 455.44,
      text: "remy's front entrance",
      type: Normal,
    },
    {
      x: 178.48,
      y: 244.64,
      text: "broken portal",
      type: Normal,
    },
    {
      x: 154,
      y: 441.84,
      text: "cool ravine that goes through a mountain",
      type: Normal,
    },
    {
      x: 253.76,
      y: 538.4,
      text: '"glory holes"',
      type: Normal,
    },
    {
      x: 530.16,
      y: 920,
      text: "weird mini-ravine; visible iron",
      type: Normal,
    },
    {
      x: 650.96,
      y: 297.04,
      text: "ravine through sand and sandstone",
      type: Normal,
    },
    {
      x: 234.08,
      y: 456.88,
      text: "big cave boi",
      type: Normal,
    },
    {
      x: 987.84,
      y: 653.04,
      text: "coochfield",
      type: Normal,
    },
    {
      x: 884.96,
      y: 586.48,
      text: "remy's back entrance",
      type: Normal,
    },
    {
      x: 827.6,
      y: 662.72,
      text: "scary hole",
      type: Normal,
    },
    {
      x: 1914.32,
      y: 850,
      text: "three-passageway pit",
      type: Normal,
    },
    {
      x: -39.92,
      y: -54.26,
      text: "cassie's ravine (feat. mitchama tunnel & railroad access)",
      type: Normal,
    },
    {
      x: -825.52,
      y: -596.08,
      text: "the sultry savanna/acacia zone",
      type: Normal,
    },
    {
      x: -975.86,
      y: -719.34,
      text: "the sandy desert",
      type: Normal,
    },
    {
      x: -1013.59,
      y: -909.47,
      text: "spidery mineshaft & ravine & bed & breakfast",
      type: Normal,
    },
    {
      x: -779.6,
      y: -193.92,
      text: "northwestern flower field",
      type: Normal,
    },
    {
      x: -128.16,
      y: -213.76,
      text: "underhill pass",
      type: Normal,
    },
    {
      x: -44.64,
      y: -127.2,
      text: "doggo sighting",
      type: Normal,
    },
    {
      x: 73.12,
      y: -989.12,
      text: "spider spawner scave",
      type: Normal,
    },
    {
      x: -430.96,
      y: -830.08,
      text: "wet broken portal",
      type: Normal,
    },
    {
      x: -538.64,
      y: -822.48,
      text: "western underwater temple",
      type: Normal,
    },
    {
      x: 713.84,
      y: -820.88,
      text: "eastern underwater temple",
      type: Normal,
    },
    {
      x: 949.36,
      y: -822.48,
      text: "ancient ruin island",
      type: Normal,
    },
    {
      x: 854.56,
      y: -577.76,
      text: "sunken ship with treasure map (pillaged by me)",
      type: Normal,
    },
    {
      x: 518.08,
      y: -805.6,
      text: "middle underwater temple",
      type: Normal,
    },
    {
      x: 779.6,
      y: -163.92,
      text: "southern underwater temple",
      type: Normal,
    },
    {
      x: -998.32,
      y: -129.68,
      text: "here be llamas",
      type: Normal,
    },
    {
      x: -986.08,
      y: -394.88,
      text: "donkey sighting",
      type: Normal,
    },
    {
      x: -782.72,
      y: -1013.6,
      text: "niagra lavafall",
      type: Normal,
    },
    {
      x: -666.48,
      y: -986.08,
      text: "hill of many holes",
      type: Normal,
    },
    {
      x: -560.16,
      y: 141.68,
      text: "extra broken portal",
      type: Normal,
    },
    {
      x: -576.72,
      y: 236.24,
      text: "swamp northern reaches",
      type: Normal,
    },
    {
      x: -387.04,
      y: 932,
      text: "baby ravine",
      type: Normal,
    },
    {
      x: -247.04,
      y: 310.24,
      text: "pillager outpost tower (looted)",
      type: Normal,
    },
    {
      x: -185.04,
      y: 436.72,
      text: "witch hut (wet)",
      type: Normal,
    },
    {
      x: -307.28,
      y: 724.24,
      text: "taiga ravine",
      type: Normal,
    },
    {
      x: -731.76,
      y: 427.68,
      text: "spruce village",
      type: Village,
    },
    {
      x: -713.76,
      y: 460.8,
      text: "spruce village ravine",
      type: Normal,
    },
    {
      x: 1451.36,
      y: 191.36,
      text: "beautiful coral :)",
      type: Normal,
    },
    {
      x: 1529.68,
      y: 138.64,
      text: "magma-powered portal (broken)",
      type: Normal,
    },
    {
      x: 1552.24,
      y: 16.72,
      text: "coral continued",
      type: Normal,
    },
    {
      x: 1305.36,
      y: 600.8,
      text: "eastern swamp",
      type: Normal,
    },
    {
      x: 1111.2,
      y: 751.36,
      text: "more flowerz",
      type: Normal,
    },
    {
      x: 1644.08,
      y: 766.4,
      text: "east village",
      type: Village,
    },
    {
      x: 2001.2,
      y: 78.4,
      text: "the savvy savanna",
      type: Normal,
    },
    {
      x: -1093.47,
      y: -341.69,
      text: "desert pyramid (skeletons?)",
      type: Normal,
    },
    {
      x: 1595.45,
      y: -874.76,
      text: "mooshroom island",
      type: Normal,
    },
    {
      x: 425.99,
      y: 504.46,
      text: "mitchama canal junction",
      type: Normal,
    },
    {
      x: 2968.63,
      y: 1304.22,
      text: "spruce s'hovel",
      type: Village,
    },
    {
      x: 2752.85,
      y: 572.36,
      text: "gravity feed mountains",
      type: Normal,
    },
    {
      x: 2579.32,
      y: 747.4,
      text: "complementary colors ravine",
      type: Normal,
    },
    {
      x: 2283.55,
      y: 207.18,
      text: "blueflower swamp",
      type: Normal,
    },
    {
      x: 2897.71,
      y: 762.49,
      text: "the rms titanic",
      type: Normal,
    },
    {
      x: 2856.97,
      y: 815.31,
      text: "pumpkintown",
      type: Village,
    },
    {
      x: 2517.45,
      y: -477.9,
      text: "turtle towers",
      type: Normal,
    },
    {
      x: 2380.13,
      y: -497.51,
      text: "redstone ravine entrance island",
      type: Normal,
    },
    {
      x: 2319.77,
      y: -710.28,
      text: "sunk sand structure",
      type: Normal,
    },
    {
      x: 2645.71,
      y: -426.59,
      text: "gerudo town",
      type: Village,
    },
    {
      x: 2743.79,
      y: -251.55,
      text: "the watery well",
      type: Normal,
    },
    {
      x: 2168.87,
      y: -535.24,
      text: "mean green ravine",
      type: Normal,
    },
    {
      x: 2389.18,
      y: -1808.83,
      text: "bi-biome cleft",
      type: Normal,
    },
    {
      x: 2671.36,
      y: -1611.15,
      text: "rome",
      type: Village,
    },
    {
      x: 2357.9,
      y: -1272.89,
      text: "vatican city",
      type: Village,
    },
    {
      x: 2642.69,
      y: -1940.11,
      text: "desert pyramid scheme",
      type: Normal,
    },
    {
      x: 2829.81,
      y: -1095.07,
      text: "the lonely acacia",
      type: Normal,
    },
    {
      x: 1222.73,
      y: -1316.89,
      text: "the hms sinkytowne",
      type: Normal,
    },
    {
      x: 1732.77,
      y: -1674.53,
      text: "beached village",
      type: Village,
    },
    {
      x: -1108.65,
      y: -106.69,
      text: "ice farm farm",
      type: Normal,
    },
    {
      x: -1179.58,
      y: -201.75,
      text: "ice farm broken portal",
      type: Normal,
    },
    {
      x: -870.23,
      y: -91.6,
      text: "munnel (mitchama tunnel) emergence",
      type: Normal,
    },
    {
      x: -844.58,
      y: -161.01,
      text: "skeleton spawner (underground, in a cave)",
      type: Normal,
    },
    {
      x: -1991.41,
      y: 480.31,
      text: "irregular ice island",
      type: Normal,
    },
    {
      x: -1371.22,
      y: 917.92,
      text: "polar bear residence",
      type: Normal,
    },
    {
      x: -1822.41,
      y: 269.05,
      text: "hay bale hovel",
      type: Village,
    },
    {
      x: 1204.63,
      y: -1956.71,
      text: "center for the drowned",
      type: Normal,
    },
    {
      x: 475.78,
      y: 1088.43,
      text: "sunflower sunlands",
      type: Normal,
    },
    {
      x: 400.33,
      y: 1690.52,
      text: "the pointy mountain",
      type: Normal,
    },
    {
      x: 427.5,
      y: 1429.47,
      text: "trapdoor town",
      type: Village,
    },
    {
      x: 1441.54,
      y: -778.19,
      text: "million guardian ruins",
      type: Normal,
    },
    {
      x: 1441.54,
      y: 1076.36,
      text: "the straight and narrow ravine",
      type: Normal,
    },
    {
      x: 1689.01,
      y: 1978.74,
      text: "gravel field mountain",
      type: Normal,
    },
    {
      x: 1770.5,
      y: 1363.07,
      text: "susurrus swamp",
      type: Normal,
    },
    {
      x: 1637.71,
      y: 1539.62,
      text: "ruined portal float",
      type: Normal,
    },
    {
      x: -117.25,
      y: 1343.45,
      text: "octoberville",
      type: Village,
    },
    {
      x: -843.07,
      y: 1867.07,
      text: "normietown",
      type: Village,
    },
    {
      x: -301.35,
      y: 1240.84,
      text: "look before you ravine",
      type: Normal,
    },
    {
      x: -687.65,
      y: 1746.35,
      text: "donkey sighting",
      type: Normal,
    },
    {
      x: -1481.37,
      y: -328.51,
      text: "pillager tower (unpillaged)",
      type: Normal,
    },
    {
      x: -1463.27,
      y: -917.01,
      text: "acacia town (pretty)",
      type: Village,
    },
    {
      x: -1156.94,
      y: -787.24,
      text: "desert pyramid 2: tokyo drift",
      type: Normal,
    },
    {
      x: -1991.41,
      y: -993.97,
      text: "painted desert gateway",
      type: Normal,
    },
    {
      x: -1829.95,
      y: -120.27,
      text: "fountain mountain village",
      type: Village,
    },
    {
      x: 2385.25,
      y: -1472.11,
      text: "vatican ravine back entrance",
      type: Normal,
    },
    {
      x: 819.15,
      y: 1404.21,
      text: "amethyst cave",
      type: Normal,
    },
    {
      x: 762.19,
      y: 942.32,
      text: "stumbleupon ravine",
      type: Normal,
    },
    {
      x: -1836.69,
      y: 1818.37,
      text: "bed & breakfast & lagoon & swamp",
      type: Normal,
    },
    {
      x: -1716.6,
      y: 1849.16,
      text: "witch's hut (conquered)",
      type: Normal,
    },
    {
      x: -1360.95,
      y: -912.92,
      text: "mitchama railroad last stop",
      type: Normal,
    },
    {
      x: 2302.19,
      y: -2138.22,
      text: "amethyst cave (deep) (beware: cave spiders)",
      type: Normal,
    },
    {
      x: 2213.28,
      y: -1768.94,
      text: "turtles for days",
      type: Normal,
    },
    {
      x: 2147.07,
      y: -2945.21,
      text: "drowned village",
      type: Normal,
    },
    {
      x: 2062.4,
      y: -2848.22,
      text: "magma trench",
      type: Normal,
    },
    {
      x: 2194.8,
      y: -2822.04,
      text: "jungle ship",
      type: Normal,
    },
    {
      x: 2906.11,
      y: -2092.26,
      text: "broken portal dig site",
      type: Normal,
    },
    {
      x: 2909.19,
      y: -2471.01,
      text: "cliffside pyramid",
      type: Normal,
    },
    {
      x: 2801.41,
      y: -2283.18,
      text: "tinytown",
      type: Village,
    },
    {
      x: 3000.02,
      y: -2977.54,
      text: "savanna ravine",
      type: Normal,
    },
    {
      x: 2402.65,
      y: -2745.06,
      text: "incomplete ship",
      type: Normal,
    },
    {
      x: 2622.82,
      y: -2815.88,
      text: "Constantinople",
      type: Village,
    },
    {
      x: 2327.21,
      y: -2081.49,
      text: "chunk anomaly mining site",
      type: Normal,
    },
    {
      x: -881.35,
      y: -220.09,
      text: "there are straight-up a lot of caves in this area",
      type: Normal,
    },
    {
      x: 169,
      y: 53,
      text: "nether portal - vatican city access",
      type: Normal,
    },
  ].map((p) => new PointOfInterest(p, 3)),
};

export default pois;
